/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import modelo.Categoria;
import modelo.Producto;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class PnlCatalogo extends javax.swing.JPanel {

    private baseDatos.OperacionesTabla db = new baseDatos.OperacionesTabla();
    private DefaultTableModel modeloTabla;

    public PnlCatalogo() {
        initComponents();
        modeloTabla = new DefaultTableModel(new String[]{"ID", "Nombre Producto"}, 0);
        tablaProductos.setModel(modeloTabla);
    }

    // Metodo para cargar las categorias en el ComboBox al entrar a la pantalla
    public void actualizarDatos() {
        try {
            cmbCategorias.removeAllItems();
            List<Categoria> cats = db.obtenerCategorias();
            for (Categoria c : cats) {
                cmbCategorias.addItem(c.getDenominacion()); // Guardamos solo el nombre por simplicidad visual
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Metodo para llenar la tabla
    private void cargarTablaProductos() {
        int indexCat = cmbCategorias.getSelectedIndex();
        if (indexCat == -1) {
            return;
        }

        modeloTabla.setRowCount(0); // Limpiar tabla
        try {
            // Obtenemos las categorias para saber el ID de la seleccionada
            List<Categoria> cats = db.obtenerCategorias();
            int idCat = cats.get(indexCat).getId();

            List<Producto> prods = db.obtenerProductosPorCategoria(idCat);
            for (Producto p : prods) {
                modeloTabla.addRow(new Object[]{p.getId(), p.getDenominacion()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCategorias = new javax.swing.JComboBox<>();
        txtNuevoProducto = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriasActionPerformed(evt);
            }
        });

        txtNuevoProducto.setText("jTextField1");

        btnAgregarProducto.setText("Crear Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(btnAgregarProducto)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        int indexCat = cmbCategorias.getSelectedIndex();
        String nom = txtNuevoProducto.getText().trim();
        if (indexCat != -1 && !nom.isEmpty()) {
            try {
                List<Categoria> cats = db.obtenerCategorias();
                int idCat = cats.get(indexCat).getId();

                db.insertarProducto(nom, idCat);
                txtNuevoProducto.setText("");
                cargarTablaProductos(); // Refresca la tabla
                javax.swing.JOptionPane.showMessageDialog(this, "Producto creado");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void cmbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriasActionPerformed
        cargarTablaProductos();
    }//GEN-LAST:event_cmbCategoriasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtNuevoProducto;
    // End of variables declaration//GEN-END:variables
}
