/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Breyner
 */
public class VtnPrincipal extends javax.swing.JFrame {

    private PnlCategorias pnlCat = new PnlCategorias();
    private PnlCatalogo pnlCatg = new PnlCatalogo();
    private PnlListas pnlLis = new PnlListas();

    public VtnPrincipal() {
        initComponents();

        pnlContenedor.add(pnlCat, "carta1");
        pnlContenedor.add(pnlCatg, "carta2");
        pnlContenedor.add(pnlLis, "carta3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuGestion = new javax.swing.JMenu();
        itemCategorias = new javax.swing.JMenuItem();
        itemCatalogo = new javax.swing.JMenuItem();
        itemListas = new javax.swing.JMenuItem();
        MnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlContenedor.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlContenedor, java.awt.BorderLayout.CENTER);

        MnuGestion.setText("Gestion");

        itemCategorias.setText("Categorias");
        itemCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriasActionPerformed(evt);
            }
        });
        MnuGestion.add(itemCategorias);

        itemCatalogo.setText("Catalogo");
        itemCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCatalogoActionPerformed(evt);
            }
        });
        MnuGestion.add(itemCatalogo);

        itemListas.setText("Mis Listas");
        itemListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListasActionPerformed(evt);
            }
        });
        MnuGestion.add(itemListas);

        jMenuBar1.add(MnuGestion);

        MnuSalir.setText("Salir");
        jMenuBar1.add(MnuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriasActionPerformed
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlContenedor.getLayout();
        layout.show(pnlContenedor, "carta1");
    }//GEN-LAST:event_itemCategoriasActionPerformed

    private void itemCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCatalogoActionPerformed
        pnlCatg.actualizarDatos(); // Refresca la base de datos
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlContenedor.getLayout();
        layout.show(pnlContenedor, "carta2");
    }//GEN-LAST:event_itemCatalogoActionPerformed

    private void itemListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListasActionPerformed
        pnlLis.actualizarDatosGlobales(); // Refresca la base de datos
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlContenedor.getLayout();
        layout.show(pnlContenedor, "carta3");
    }//GEN-LAST:event_itemListasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuGestion;
    private javax.swing.JMenu MnuSalir;
    private javax.swing.JMenuItem itemCatalogo;
    private javax.swing.JMenuItem itemCategorias;
    private javax.swing.JMenuItem itemListas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
